language: ruby
rvm:
 - "2.2.0"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database pubs_portal_test;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake

notifications:
  slack: joypactdev:ZDiuFI4GDQJ0KQzTgJljV29y

addons:
  code_climate:
    repo_token: e49d3aa9c51decadae274fde90b6e34d14082c575af18109752339ed38ac6bae
  # sauce_connect:
  #   username: "davidwosk1"
  #   access_key: "0760394d-b006-4432-a9da-fabc6854f154"

# env:
#  - USE_SAUCE_LABS=true
