# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3b6a3621db942d3d40a34b7061c2c5a069e75fe6f3803aa1b5415e2af8af1d9bb907c9bffc50ee456998a9003724702a50cae7f437768b5de9fb5a2ae2eddf1

test:
  secret_key_base: 2e8f4132777d1017cdfcb08283e7535b14a4c6878d328a35c91657eef803a93741d41338648f95e9c9099c23e0210612d9ba2e5ddc228fe0bd2c9800bfbcd385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
